#include "nigelcrypt.hpp"

#include <cstdlib>
#include <iostream>
#include <memory>
#include <vector>

// Example: runtime-only decryption using a pre-packed encrypted blob.
//
// Steps:
// 1) Create a plaintext file (NOT checked into source control).
// 2) Run tools/nigelcrypt_pack.exe to generate a header with ciphertext.
// 3) Include that header here and decrypt at runtime using a passphrase from
//    an environment variable.
//
// Build (MSVC):
//   cl /std:c++20 /EHsc example.cpp
//
// Build (CMake-less, MinGW, etc.) make sure to link:
//   bcrypt.lib and crypt32.lib (MSVC) or -lbcrypt -lcrypt32 (MinGW).

// Generated by tools/nigelcrypt_pack (example path; you generate this).
#include "packed/secret_blob.hpp"

int main() {
    using nigelcrypt::PasswordKeyProvider;
    using nigelcrypt::SecureString;

    // Passphrase must NOT be a string literal in your binary.
    // Provide it at runtime, e.g. via environment variable.
    const char* pass = std::getenv("NIGELCRYPT_PASSPHRASE");
    if (!pass || !*pass) {
        std::cerr << "Set NIGELCRYPT_PASSPHRASE before running.\n";
        return 1;
    }

    // Configure key provider from the generated header parameters.
    std::vector<uint8_t> salt(
        nigelcrypt_packed::secret_salt.begin(),
        nigelcrypt_packed::secret_salt.end()
    );
    auto provider = std::make_shared<PasswordKeyProvider>(
        std::string(pass),
        salt,
        nigelcrypt_packed::secret_iterations,
        nigelcrypt_packed::secret_key_id
    );
    nigelcrypt::set_key_provider(provider);

    // Import the encrypted envelope (ciphertext only).
    std::vector<uint8_t> blob(
        nigelcrypt_packed::secret_blob.begin(),
        nigelcrypt_packed::secret_blob.end()
    );
    if (blob.empty()) {
        std::cerr << "Packed blob is empty. Generate it with nigelcrypt_pack.\n";
        return 1;
    }

    auto s = SecureString::import_envelope(blob);
    auto plain = s.decrypt();
    std::cout << "Decrypted: " << plain.c_str() << "\n";
    return 0;
}
